// Host-only oracle. Uses cloudflared's unchanged generated schema and its
// pinned RPC runtime; no Go code is linked into firmware. Synthetic data only.
package main

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sync/atomic"
	"time"

	proto "github.com/cloudflare/cloudflared/tunnelrpc/proto"
	capnp "zombiezen.com/go/capnproto2"
	"zombiezen.com/go/capnproto2/rpc"
	wire "zombiezen.com/go/capnproto2/std/capnp/rpc"
)

func must(err error) {
	if err != nil {
		panic(err)
	}
}
func pattern(n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = byte(i)
	}
	return b
}
func require(ok bool, field string) error {
	if !ok {
		return fmt.Errorf("synthetic field mismatch: %s", field)
	}
	return nil
}

func response(seg *capnp.Segment, ret wire.Return, mode string) {
	payload, err := ret.NewResults()
	must(err)
	result, err := proto.NewRegistrationServer_registerConnection_Results(seg)
	must(err)
	must(payload.SetContentPtr(result.ToPtr()))
	value, err := result.NewResult()
	must(err)
	if mode == "retry" || mode == "permanent" || mode == "negative" {
		ce, err := value.Result().NewError()
		must(err)
		must(ce.SetCause("Synthetic registration rejection"))
		ce.SetShouldRetry(mode != "permanent")
		ce.SetRetryAfter(1500000001)
		if mode == "negative" {
			ce.SetRetryAfter(-1)
		}
	} else {
		details, err := value.Result().NewConnectionDetails()
		must(err)
		must(details.SetUuid(pattern(16)))
		must(details.SetLocationName("SOF"))
		details.SetTunnelIsRemotelyManaged(mode != "local")
	}
}

func fixture(name string, multi bool) []byte {
	var arena capnp.Arena = capnp.SingleSegment(nil)
	if multi {
		arena = capnp.MultiSegment([][]byte{make([]byte, 0, 8)})
	}
	msg, seg, err := capnp.NewMessage(arena)
	must(err)
	root, err := wire.NewRootMessage(seg)
	must(err)
	if name == "abort" {
		ex, err := root.NewAbort()
		must(err)
		must(ex.SetReason("Synthetic abort"))
	} else {
		ret, err := root.NewReturn()
		must(err)
		ret.SetAnswerId(1)
		switch name {
		case "bootstrap", "promise":
			ret.SetAnswerId(0)
			p, err := ret.NewResults()
			must(err)
			must(p.SetContentPtr(capnp.NewInterface(seg, 0).ToPtr()))
			caps, err := p.NewCapTable(1)
			must(err)
			if name == "promise" {
				caps.At(0).SetSenderPromise(37)
			} else {
				caps.At(0).SetSenderHosted(37)
			}
		case "exception":
			ex, err := ret.NewException()
			must(err)
			must(ex.SetReason("Synthetic RPC failure"))
		case "unregister":
			ret.SetAnswerId(2)
			p, err := ret.NewResults()
			must(err)
			result, err := proto.NewRegistrationServer_unregisterConnection_Results(seg)
			must(err)
			must(p.SetContentPtr(result.ToPtr()))
		default:
			response(seg, ret, name)
			if name == "wrong_question" {
				ret.SetAnswerId(99)
			}
		}
	}
	data, err := msg.Marshal()
	must(err)
	return data
}

func generate(dir string) {
	must(os.MkdirAll(dir, 0755))
	var header bytes.Buffer
	header.WriteString("/* Generated by tools/rpc_reference using cloudflared 2026.9.1 and capnproto2 v2.18.0. Synthetic only. */\n")
	for _, name := range []string{"bootstrap", "success", "retry", "permanent", "negative", "local", "exception", "abort", "wrong_question", "promise", "unregister"} {
		for _, multi := range []bool{false, true} {
			suffix := ""
			if multi {
				suffix = "_multi"
			}
			data := fixture(name, multi)
			must(os.WriteFile(filepath.Join(dir, name+suffix+".bin"), data, 0644))
			fmt.Fprintf(&header, "static const unsigned char rpc_%s%s[] = {\n", name, suffix)
			for i, b := range data {
				if i%16 == 0 {
					header.WriteString("    ")
				}
				fmt.Fprintf(&header, "0x%02x,", b)
				if i%16 == 15 || i == len(data)-1 {
					header.WriteByte('\n')
				}
			}
			header.WriteString("};\n")
		}
	}
	must(os.WriteFile(filepath.Join(dir, "rpc_vectors.h"), header.Bytes(), 0644))
	fmt.Println("Generated 22 independent RPC fixtures")
}

type testServer struct{ registered, unregistered atomic.Bool }

func (s *testServer) RegisterConnection(p proto.RegistrationServer_registerConnection) error {
	auth, err := p.Params.Auth()
	if err != nil {
		return err
	}
	a, err := auth.AccountTag()
	if err != nil {
		return err
	}
	if err = require(a == "0123456789abcdef0123456789abcdef", "account"); err != nil {
		return err
	}
	secret, err := auth.TunnelSecret()
	if err != nil {
		return err
	}
	if err = require(bytes.Equal(secret, pattern(36)), "secret length/content"); err != nil {
		return err
	}
	id, err := p.Params.TunnelId()
	if err != nil {
		return err
	}
	if err = require(bytes.Equal(id, pattern(16)), "tunnel ID"); err != nil {
		return err
	}
	if err = require(p.Params.ConnIndex() == 2, "connection index"); err != nil {
		return err
	}
	opt, err := p.Params.Options()
	if err != nil {
		return err
	}
	if err = require(!opt.ReplaceExisting() && opt.CompressionQuality() == 0 && opt.NumPreviousAttempts() == 3, "options"); err != nil {
		return err
	}
	ip, err := opt.OriginLocalIp()
	if err != nil {
		return err
	}
	if err = require(bytes.Equal(ip, []byte{192, 0, 2, 1}), "local IP"); err != nil {
		return err
	}
	client, err := opt.Client()
	if err != nil {
		return err
	}
	cid, err := client.ClientId()
	if err != nil {
		return err
	}
	if err = require(bytes.Equal(cid, pattern(16)), "connector UUID"); err != nil {
		return err
	}
	version, err := client.Version()
	if err != nil {
		return err
	}
	arch, err := client.Arch()
	if err != nil {
		return err
	}
	features, err := client.Features()
	if err != nil {
		return err
	}
	if err = require(version == "esp-cf-test" && arch == "host-test" && features.Len() == 2, "client metadata"); err != nil {
		return err
	}
	remote, err := features.At(0)
	if err != nil {
		return err
	}
	serialized, err := features.At(1)
	if err != nil {
		return err
	}
	if err = require(remote == "allow_remote_config" && serialized == "serialized_headers", "supported features"); err != nil {
		return err
	}
	value, err := p.Results.NewResult()
	if err != nil {
		return err
	}
	details, err := value.Result().NewConnectionDetails()
	if err != nil {
		return err
	}
	if err = details.SetUuid(pattern(16)); err != nil {
		return err
	}
	if err = details.SetLocationName("SOF"); err != nil {
		return err
	}
	details.SetTunnelIsRemotelyManaged(true)
	s.registered.Store(true)
	return nil
}
func (s *testServer) UnregisterConnection(p proto.RegistrationServer_unregisterConnection) error {
	if !s.registered.Load() {
		return fmt.Errorf("unregister before register")
	}
	s.unregistered.Store(true)
	return nil
}
func (s *testServer) UpdateLocalConfiguration(p proto.RegistrationServer_updateLocalConfiguration) error {
	return fmt.Errorf("unexpected local configuration")
}

type stdio struct{}

func (stdio) Read(p []byte) (int, error)  { return os.Stdin.Read(p) }
func (stdio) Write(p []byte) (int, error) { return os.Stdout.Write(p) }
func (stdio) Close() error                { return nil }

type logger struct{}

func (logger) Infof(context.Context, string, ...interface{})  {}
func (logger) Errorf(context.Context, string, ...interface{}) {}
func serve() {
	s := new(testServer)
	conn := rpc.NewConn(rpc.StreamTransport(stdio{}), rpc.MainInterface(proto.RegistrationServer_ServerToClient(s).Client), rpc.ConnLog(logger{}))
	select {
	case <-conn.Done():
	case <-time.After(15 * time.Second):
		_ = conn.Close()
		panic("RPC conversation timed out")
	}
	if !s.registered.Load() || !s.unregistered.Load() {
		panic("incomplete RPC conversation")
	}
	fmt.Fprintln(os.Stderr, "PASS: official Go RPC server decoded and executed registration and unregister")
}

func inspect(dir string) {
	for _, name := range []string{"bootstrap", "register", "finish_bootstrap", "finish_register", "unregister", "finish_unregister", "release"} {
		data, err := os.ReadFile(filepath.Join(dir, name+".bin"))
		must(err)
		msg, err := capnp.Unmarshal(data)
		must(err)
		root, err := wire.ReadRootMessage(msg)
		must(err)
		switch name {
		case "bootstrap":
			b, err := root.Bootstrap()
			must(err)
			must(require(b.QuestionId() == 0, "bootstrap question"))
		case "register", "unregister":
			c, err := root.Call()
			must(err)
			must(require(c.InterfaceId() == proto.RegistrationServer_TypeID, "interface ID"))
			t, err := c.Target()
			must(err)
			must(require(t.ImportedCap() == 37, "imported capability"))
			must(require(c.SendResultsTo().Which() == wire.Call_sendResultsTo_Which_caller, "result routing"))
			if name == "register" {
				must(require(c.QuestionId() == 1 && c.MethodId() == 0, "registration method"))
				payload, err := c.Params()
				must(err)
				ptr, err := payload.ContentPtr()
				must(err)
				params := proto.RegistrationServer_registerConnection_Params{Struct: ptr.Struct()}
				auth, err := params.Auth()
				must(err)
				secret, err := auth.TunnelSecret()
				must(err)
				must(require(bytes.Equal(secret, pattern(36)), "encoded 36-byte secret"))
			} else {
				must(require(c.QuestionId() == 2 && c.MethodId() == 1, "unregister method"))
			}
		case "release":
			r, err := root.Release()
			must(err)
			must(require(r.Id() == 37 && r.ReferenceCount() == 1, "release refcount"))
		default:
			f, err := root.Finish()
			must(err)
			id := uint32(0)
			if name == "finish_register" {
				id = 1
			}
			if name == "finish_unregister" {
				id = 2
			}
			must(require(f.QuestionId() == id && f.ReleaseResultCaps() == (id != 0), "finish lifecycle"))
		}
	}
	fmt.Println("PASS: official Go codec inspected all seven C message types")
}
func main() {
	defer func() {
		if e := recover(); e != nil {
			fmt.Fprintln(os.Stderr, e)
			os.Exit(1)
		}
	}()
	if len(os.Args) < 2 {
		panic("use generate DIR, inspect DIR, or serve")
	}
	switch os.Args[1] {
	case "generate":
		generate(os.Args[2])
	case "inspect":
		inspect(os.Args[2])
	case "serve":
		serve()
	default:
		panic(io.EOF)
	}
}
