"""Independent Python stdlib base64/JSON/framing vectors, not RPC fixtures.

Only synthetic credentials. Header mapping follows the pinned header.go;
Python's codec is independent of the C implementation. No network or secrets.
"""
import argparse
import base64
import json
import pathlib
import struct

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEST = ROOT / "tests/fixtures/reference_vectors.h"


def generate():
    pairs = [("Set-Cookie", "a=1; Path=/"), ("Set-Cookie", "b=2"),
             ("X-Empty", ""), ("X-Punctuation", ":;/+"), ("X-UTF8", "тест")]
    raw = lambda s: base64.b64encode(s.encode()).rstrip(b"=").decode()
    headers = ";".join(raw(k) + ":" + raw(v) for k, v in pairs)
    credentials = {"a": "0123456789abcdef0123456789abcdef",
                   "s": base64.b64encode(bytes(range(32))).decode(),
                   "t": "00112233-4455-4677-8899-aabbccddeeff"}
    token = base64.b64encode(json.dumps(credentials, separators=(",", ":")).encode())
    secret_tokens = []
    for size in (31, 36, 64, 128, 129):
        variant = dict(credentials, s=base64.b64encode(bytes(range(size))).decode())
        secret_tokens.append((f"gold_token_secret_{size}", base64.b64encode(
            json.dumps(variant, separators=(",", ":")).encode())))
    # Segment zero contains a null root pointer. Second segment is unused data;
    # framing validity does not imply a valid RegistrationServer RPC message.
    single = struct.pack("<IIQ", 0, 1, 0)
    multi = struct.pack("<IIIIQQ", 1, 1, 1, 0, 0, 0x0102030405060708)
    def dns_name(name):
        return b"".join(bytes([len(label)]) + label.encode() for label in name.split('.')) + b'\0'
    srv_name = '_v2-origintunneld._tcp.argotunnel.com'
    srv_question = dns_name(srv_name) + struct.pack('!HH', 33, 1)
    srv_query = struct.pack('!6H', 0x1234, 0x0100, 1, 0, 0, 1) + srv_question + struct.pack('!BHHIH', 0, 41, 1232, 0, 0)
    srv_response = struct.pack('!6H', 0x1234, 0x8180, 1, 2, 0, 0) + srv_question
    for region in (1, 2):
        rdata = struct.pack('!HHH', region, 1, 7844) + dns_name(f'region{region}.v2.argotunnel.com')
        srv_response += b'\xc0\x0c' + struct.pack('!HHIH', 33, 1, 86400, len(rdata)) + rdata
    a_question = dns_name('region1.v2.argotunnel.com') + struct.pack('!HH', 1, 1)
    a_response = struct.pack('!6H', 0x1234, 0x8180, 1, 2, 0, 0) + a_question
    for ip in (bytes([192, 0, 2, 1]), bytes([198, 51, 100, 2])):
        a_response += b'\xc0\x0c' + struct.pack('!HHIH', 1, 1, 300, 4) + ip
    result = "/* Generated by tools/generate_fixtures.py; synthetic inputs only. */\n"
    for name, data in [("gold_headers", headers.encode()), ("gold_token", token),
                       ("gold_single_segment", single), ("gold_multi_segment", multi),
                       ("gold_dns_query",srv_query), ("gold_dns_srv",srv_response), ("gold_dns_a",a_response)] + secret_tokens:
        result += f"static const unsigned char {name}[] = {{\n"
        for offset in range(0, len(data), 16):
            result += "    " + ", ".join(f"0x{x:02x}" for x in data[offset:offset+16]) + ",\n"
        result += "};\n"
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not DEST.exists() or DEST.read_text(encoding="utf-8") != content:
            raise SystemExit("Reference fixtures differ; run tools/generate_fixtures.py")
        print("Reference fixtures match independent Python generator")
    else:
        DEST.parent.mkdir(parents=True, exist_ok=True)
        DEST.write_text(content, encoding="utf-8", newline="\n")
        print("Wrote tests/fixtures/reference_vectors.h")
